-- Catálogos app-wide (barrido de selects hardcodeados → erp_parameters).
-- Convención param_key='CATALOGO.<TABLA>.<CODIGO>'. Valores preservados exactos de los <option> originales.
-- Conflictos resueltos: TIPO_MOVIMIENTO_CONTABLE (DEBE/HABER) vs TIPO_MOVIMIENTO_BANCARIO (DEBITO/CREDITO);
-- CATEGORIA_CLIENTE (enum) vs TIPO_PERSONA (natural/jurídica) vs SEGMENTO_CLIENTE (ids). MONEDA: +EUR/GBP/JPY/CHF (PEN/USD ya en V23).
INSERT INTO erp_parameters (tenant_id, param_group, param_key, param_value, param_description, is_active, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion, activo, editable, tipo)
VALUES
  (NULL, 'CATALOGO', 'CATALOGO.MONEDA.EUR', '€ (EUR)', 'MONEDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MONEDA.GBP', '£ (GBP)', 'MONEDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MONEDA.JPY', '¥ (JPY)', 'MONEDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MONEDA.CHF', 'CHF', 'MONEDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DEVOLUCION.DEVOLUCION', 'Devolución', 'TIPO_DEVOLUCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DEVOLUCION.CAMBIO', 'Cambio', 'TIPO_DEVOLUCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DEVOLUCION.NOTA_CREDITO', 'Nota de Crédito', 'TIPO_DEVOLUCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CONTRATO.MARCO', 'Marco', 'TIPO_CONTRATO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CONTRATO.ESPECIFICO', 'Específico', 'TIPO_CONTRATO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CONTRATO.SERVICIO', 'Servicio', 'TIPO_CONTRATO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CONDICION_SUNAT.HABIDO', 'Habido', 'CONDICION_SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CONDICION_SUNAT.NO_HABIDO', 'No Habido', 'CONDICION_SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CONDICION_SUNAT.NO_HALLADO', 'No Hallado', 'CONDICION_SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CONDICION_PAGO.CONTADO', 'Contado', 'CONDICION_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CONDICION_PAGO.CREDITO_15', 'Crédito 15 días', 'CONDICION_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CONDICION_PAGO.CREDITO_30', 'Crédito 30 días', 'CONDICION_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CONDICION_PAGO.CREDITO_60', 'Crédito 60 días', 'CONDICION_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CONDICION_PAGO.CREDITO_90', 'Crédito 90 días', 'CONDICION_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_COMPROBANTE.FACTURA', 'Factura', 'TIPO_COMPROBANTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_COMPROBANTE.BOLETA', 'Boleta', 'TIPO_COMPROBANTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_COMPROBANTE.NOTA_CREDITO', 'Nota de Crédito', 'TIPO_COMPROBANTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.UNIDAD_MEDIDA.UND', 'UND', 'UNIDAD_MEDIDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.UNIDAD_MEDIDA.KG', 'KG', 'UNIDAD_MEDIDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.UNIDAD_MEDIDA.LT', 'LT', 'UNIDAD_MEDIDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.UNIDAD_MEDIDA.MT', 'MT', 'UNIDAD_MEDIDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.UNIDAD_MEDIDA.CAJA', 'CAJA', 'UNIDAD_MEDIDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.UNIDAD_MEDIDA.HRS', 'HRS', 'UNIDAD_MEDIDA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_BUSQUEDA_HISTORIAL_PRECIOS.sku', 'SKU', 'TIPO_BUSQUEDA_HISTORIAL_PRECIOS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_BUSQUEDA_HISTORIAL_PRECIOS.producto', 'ID Producto', 'TIPO_BUSQUEDA_HISTORIAL_PRECIOS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_BUSQUEDA_HISTORIAL_PRECIOS.proveedor', 'ID Proveedor', 'TIPO_BUSQUEDA_HISTORIAL_PRECIOS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_ASIENTO_CONTABLE.MANUAL', 'Manual', 'TIPO_ASIENTO_CONTABLE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_ASIENTO_CONTABLE.CIERRE', 'Cierre', 'TIPO_ASIENTO_CONTABLE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.FRECUENCIA_RECURRENCIA.MENSUAL', 'Mensual', 'FRECUENCIA_RECURRENCIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.FRECUENCIA_RECURRENCIA.TRIMESTRAL', 'Trimestral', 'FRECUENCIA_RECURRENCIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.FRECUENCIA_RECURRENCIA.SEMESTRAL', 'Semestral', 'FRECUENCIA_RECURRENCIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.FRECUENCIA_RECURRENCIA.ANUAL', 'Anual', 'FRECUENCIA_RECURRENCIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_CONTABLE.DEBE', 'DEBE', 'TIPO_MOVIMIENTO_CONTABLE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_CONTABLE.HABER', 'HABER', 'TIPO_MOVIMIENTO_CONTABLE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_BANCARIO.DEBITO', 'Débito', 'TIPO_MOVIMIENTO_BANCARIO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_BANCARIO.CREDITO', 'Crédito', 'TIPO_MOVIMIENTO_BANCARIO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CIERRE_CONTABLE.MENSUAL', 'Cierre Mensual', 'TIPO_CIERRE_CONTABLE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CIERRE_CONTABLE.ANUAL', 'Cierre Anual (todos los períodos del año)', 'TIPO_CIERRE_CONTABLE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ORIGEN_PARTIDA_CONCILIACION.BANCO', 'Banco', 'ORIGEN_PARTIDA_CONCILIACION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ORIGEN_PARTIDA_CONCILIACION.LIBRO', 'Libro', 'ORIGEN_PARTIDA_CONCILIACION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_TRANSACCION.VENTA', 'Venta', 'TIPO_TRANSACCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_TRANSACCION.COMPRA', 'Compra', 'TIPO_TRANSACCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_TRANSACCION.NOMINA', 'Nómina', 'TIPO_TRANSACCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_TRANSACCION.TESORERIA', 'Tesorería', 'TIPO_TRANSACCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_TRANSACCION.INVENTARIO', 'Inventario', 'TIPO_TRANSACCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_TRANSACCION.LOGISTICA', 'Logística', 'TIPO_TRANSACCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CAMPO_ORIGEN_REGLA_ASIENTO.TOTAL', 'Total', 'CAMPO_ORIGEN_REGLA_ASIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CAMPO_ORIGEN_REGLA_ASIENTO.BASE', 'Base', 'CAMPO_ORIGEN_REGLA_ASIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CAMPO_ORIGEN_REGLA_ASIENTO.IGV', 'IGV', 'CAMPO_ORIGEN_REGLA_ASIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CAMPO_ORIGEN_REGLA_ASIENTO.ISC', 'ISC', 'CAMPO_ORIGEN_REGLA_ASIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CAMPO_ORIGEN_REGLA_ASIENTO.OTROS_CARGOS', 'Otros cargos', 'CAMPO_ORIGEN_REGLA_ASIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.PERIODO_DIAS_ANALISIS.90', 'Últimos 90 días', 'PERIODO_DIAS_ANALISIS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.PERIODO_DIAS_ANALISIS.180', 'Últimos 180 días', 'PERIODO_DIAS_ANALISIS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.PERIODO_DIAS_ANALISIS.365', 'Últimos 365 días', 'PERIODO_DIAS_ANALISIS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ASN.PENDIENTE', 'Pendiente', 'ESTADO_ASN', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ASN.CONFORME', 'Conforme', 'ESTADO_ASN', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ASN.CON_DIFERENCIAS', 'Con diferencias', 'ESTADO_ASN', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_UBICACION.PICKING', 'Picking', 'TIPO_UBICACION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_UBICACION.ALMACENAMIENTO', 'Almacenamiento', 'TIPO_UBICACION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_UBICACION.RECEPCION', 'Recepción', 'TIPO_UBICACION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_UBICACION.DESPACHO', 'Despacho', 'TIPO_UBICACION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REFERENCIA_MOVIMIENTO.ORDEN_COMPRA', 'Orden de Compra', 'TIPO_REFERENCIA_MOVIMIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REFERENCIA_MOVIMIENTO.PEDIDO_VENTA', 'Pedido de Venta', 'TIPO_REFERENCIA_MOVIMIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REFERENCIA_MOVIMIENTO.TRANSFERENCIA', 'Transferencia', 'TIPO_REFERENCIA_MOVIMIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REFERENCIA_MOVIMIENTO.AJUSTE', 'Ajuste', 'TIPO_REFERENCIA_MOVIMIENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DESCUENTO.PORCENTAJE', '%', 'TIPO_DESCUENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DESCUENTO.MONTO', 'S/', 'TIPO_DESCUENTO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_BUSQUEDA_VENTA.ticket', 'N° Ticket', 'TIPO_BUSQUEDA_VENTA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_BUSQUEDA_VENTA.id', 'ID de Venta', 'TIPO_BUSQUEDA_VENTA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CRITERIO_ORDEN_PRODUCTOS.sales', 'Más vendidos', 'CRITERIO_ORDEN_PRODUCTOS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CRITERIO_ORDEN_PRODUCTOS.price-asc', 'Menor precio', 'CRITERIO_ORDEN_PRODUCTOS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CRITERIO_ORDEN_PRODUCTOS.price-desc', 'Mayor precio', 'CRITERIO_ORDEN_PRODUCTOS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CRITERIO_ORDEN_PRODUCTOS.rating', 'Mejor valorados', 'CRITERIO_ORDEN_PRODUCTOS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTRATEGIA_PICKING.ZONE', 'Por Zona', 'ESTRATEGIA_PICKING', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTRATEGIA_PICKING.WAVE', 'Por Oleada', 'ESTRATEGIA_PICKING', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTRATEGIA_PICKING.CLUSTER', 'Cluster', 'ESTRATEGIA_PICKING', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MODALIDAD_TRASLADO_SUNAT.01', '01 — Transporte Público', 'MODALIDAD_TRASLADO_SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MODALIDAD_TRASLADO_SUNAT.02', '02 — Transporte Privado', 'MODALIDAD_TRASLADO_SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.NIVEL_JERARQUICO_CATEGORIA.0', 'Nivel 0 - Raíz', 'NIVEL_JERARQUICO_CATEGORIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.NIVEL_JERARQUICO_CATEGORIA.1', 'Nivel 1', 'NIVEL_JERARQUICO_CATEGORIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.NIVEL_JERARQUICO_CATEGORIA.2', 'Nivel 2', 'NIVEL_JERARQUICO_CATEGORIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.NIVEL_JERARQUICO_CATEGORIA.3', 'Nivel 3', 'NIVEL_JERARQUICO_CATEGORIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DIRECCION.FISCAL', 'Fiscal', 'TIPO_DIRECCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DIRECCION.ENVIO', 'Envío', 'TIPO_DIRECCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DIRECCION.AMBAS', 'Fiscal y Envío', 'TIPO_DIRECCION', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CATEGORIA_CLIENTE.VIP', 'VIP', 'CATEGORIA_CLIENTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CATEGORIA_CLIENTE.REGULAR', 'Regular', 'CATEGORIA_CLIENTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CATEGORIA_CLIENTE.OCASIONAL', 'Ocasional', 'CATEGORIA_CLIENTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.CATEGORIA_CLIENTE.MAYORISTA', 'Mayorista', 'CATEGORIA_CLIENTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_PERSONA.PERSONA_NATURAL', 'Persona Natural', 'TIPO_PERSONA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_PERSONA.PERSONA_JURIDICA', 'Persona Jurídica', 'TIPO_PERSONA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.SEGMENTO_CLIENTE.1', 'VIP', 'SEGMENTO_CLIENTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.SEGMENTO_CLIENTE.2', 'Regular', 'SEGMENTO_CLIENTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.SEGMENTO_CLIENTE.3', 'Ocasional', 'SEGMENTO_CLIENTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.SEGMENTO_CLIENTE.4', 'Mayorista', 'SEGMENTO_CLIENTE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DOCUMENTO_IDENTIDAD.DNI', 'DNI', 'TIPO_DOCUMENTO_IDENTIDAD', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DOCUMENTO_IDENTIDAD.RUC', 'RUC', 'TIPO_DOCUMENTO_IDENTIDAD', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DOCUMENTO_IDENTIDAD.CE', 'Carnet de Extranjería', 'TIPO_DOCUMENTO_IDENTIDAD', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_DOCUMENTO_IDENTIDAD.PASAPORTE', 'Pasaporte', 'TIPO_DOCUMENTO_IDENTIDAD', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.BCP — Banco de Crédito del Perú', 'BCP — Banco de Crédito del Perú', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.BBVA Perú', 'BBVA Perú', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Scotiabank Perú', 'Scotiabank Perú', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Interbank', 'Interbank', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Banco Pichincha', 'Banco Pichincha', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Banco GNB', 'Banco GNB', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Banco Falabella', 'Banco Falabella', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Banbif', 'Banbif', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Banco Ripley', 'Banco Ripley', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Caja Municipal Arequipa', 'Caja Municipal Arequipa', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Caja Huancayo', 'Caja Huancayo', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.BANCO.Banco de la Nación', 'Banco de la Nación', 'BANCO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_BANCARIA.CORRIENTE', 'Corriente', 'TIPO_CUENTA_BANCARIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_BANCARIA.AHORROS', 'Ahorros', 'TIPO_CUENTA_BANCARIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_BANCARIA.CTS', 'CTS', 'TIPO_CUENTA_BANCARIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_BANCARIA.DETRACCIONES', 'Detracciones', 'TIPO_CUENTA_BANCARIA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_CAJA.INGRESO', 'Ingreso', 'TIPO_MOVIMIENTO_CAJA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_CAJA.EGRESO', 'Egreso', 'TIPO_MOVIMIENTO_CAJA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_CAJA.TRANSFERENCIA', 'Transferencia', 'TIPO_MOVIMIENTO_CAJA', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_PAGO.PROVEEDOR', 'Proveedor', 'TIPO_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_PAGO.NOMINA', 'Nómina', 'TIPO_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_PAGO.IMPUESTO', 'Impuesto', 'TIPO_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_PAGO.OTRO', 'Otro', 'TIPO_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO.TRANSFERENCIA', 'Transferencia Bancaria', 'METODO_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO.CHEQUE', 'Cheque', 'METODO_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO.EFECTIVO', 'Efectivo', 'METODO_PAGO', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog')
ON CONFLICT (tenant_id, param_key) DO NOTHING;
