-- Catálogos por módulo (RRHH, compras, logística, contabilidad, ventas/POS).
-- Códigos DERIVADOS de los enums/valores reales del backend (no de los <option> hardcodeados,
-- que en varios casos estaban incompletos o desalineados). Convención V23/V24:
--   param_key = 'CATALOGO.<TABLA>.<CODIGO>'  ·  tenant_id NULL (global)  ·  tipo 'catalog'
-- Sirven al endpoint GET /users/api/system/parameters/catalog/{tabla} y a <app-catalog-select>.

INSERT INTO erp_parameters (tenant_id, param_group, param_key, param_value, param_description, is_active, fecha_creacion, usuario_creacion, fecha_modificacion, usuario_modificacion, activo, editable, tipo)
VALUES
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CAPACITACION.PLANIFICADO', 'Planificado', 'Estado de capacitación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CAPACITACION.EN_CURSO', 'En Curso', 'Estado de capacitación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CAPACITACION.COMPLETADO', 'Completado', 'Estado de capacitación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CAPACITACION.CANCELADO', 'Cancelado', 'Estado de capacitación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTEO_INVENTARIO.EN_PROCESO', 'En Proceso', 'Estado de conteo de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTEO_INVENTARIO.CERRADO', 'Cerrado', 'Estado de conteo de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTEO_INVENTARIO.AJUSTADO', 'Ajustado', 'Estado de conteo de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTRATO_LABORAL.ACTIVO', 'Activo', 'Estado de contrato laboral', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTRATO_LABORAL.FINALIZADO', 'Finalizado', 'Estado de contrato laboral', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTRATO_LABORAL.SUSPENDIDO', 'Suspendido', 'Estado de contrato laboral', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTRATO_LABORAL.RENOVADO', 'Renovado', 'Estado de contrato laboral', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTRATO_PROVEEDOR.VIGENTE', 'Vigente', 'Estado de contrato con proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTRATO_PROVEEDOR.VENCIDO', 'Vencido', 'Estado de contrato con proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_CONTRATO_PROVEEDOR.RESCINDIDO', 'Rescindido', 'Estado de contrato con proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_COTIZACION.CREADA', 'Creada', 'Estado de cotización', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_COTIZACION.ENVIADA', 'Enviada', 'Estado de cotización', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_COTIZACION.EN_RESPUESTA', 'En Respuesta', 'Estado de cotización', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_COTIZACION.ADJUDICADA', 'Adjudicada', 'Estado de cotización', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_COTIZACION.CONVERTIDA_OC', 'Convertida a Orden de Compra', 'Estado de cotización', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_COMPRA.BORRADOR', 'Borrador', 'Estado de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_COMPRA.ENVIADA', 'Enviada', 'Estado de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_COMPRA.ACEPTADA', 'Aceptada', 'Estado de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_COMPRA.COMPLETADA', 'Completada', 'Estado de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_LOGISTICA.REQUESTED', 'Solicitada', 'Estado de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_LOGISTICA.APPROVED', 'Aprobada', 'Estado de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_LOGISTICA.REJECTED', 'Rechazada', 'Estado de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_LOGISTICA.IN_TRANSIT_TO_WAREHOUSE', 'En Tránsito al Almacén', 'Estado de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_LOGISTICA.RECEIVED', 'Recibida', 'Estado de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_LOGISTICA.INSPECTED', 'Inspeccionada', 'Estado de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_LOGISTICA.REFUNDED', 'Reembolsada', 'Estado de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_DEVOLUCION_LOGISTICA.CANCELLED', 'Cancelada', 'Estado de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ENVIO.PENDING_DISPATCH', 'Pendiente de Despacho', 'Estado de envío', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ENVIO.DISPATCHED', 'Despachado', 'Estado de envío', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ENVIO.IN_TRANSIT', 'En Tránsito', 'Estado de envío', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ENVIO.OUT_FOR_DELIVERY', 'En Reparto', 'Estado de envío', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ENVIO.DELIVERED', 'Entregado', 'Estado de envío', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ENVIO.FAILED_DELIVERY', 'Entrega Fallida', 'Estado de envío', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ENVIO.RETURNED', 'Devuelto', 'Estado de envío', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ENVIO.CANCELLED', 'Cancelado', 'Estado de envío', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_EVALUACION.BORRADOR', 'Borrador', 'Estado de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_EVALUACION.COMPLETADA', 'Completada', 'Estado de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_EVALUACION.APROBADA', 'Aprobada', 'Estado de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_EVALUACION.CANCELADA', 'Cancelada', 'Estado de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_FACTURA_PROVEEDOR.PENDIENTE', 'Pendiente', 'Estado de factura de proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_FACTURA_PROVEEDOR.PENDIENTE_REVISION', 'Pendiente de Revisión', 'Estado de factura de proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_FACTURA_PROVEEDOR.APROBADA', 'Aprobada', 'Estado de factura de proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_FACTURA_PROVEEDOR.RECHAZADA', 'Rechazada', 'Estado de factura de proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_GUIA_REMISION.EMITIDA', 'Emitida', 'Estado de guía de remisión', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_GUIA_REMISION.EN_TRASLADO', 'En Traslado', 'Estado de guía de remisión', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_GUIA_REMISION.RECIBIDA', 'Recibida', 'Estado de guía de remisión', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_GUIA_REMISION.ANULADA', 'Anulada', 'Estado de guía de remisión', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ORDEN_COMPRA.BORRADOR', 'Borrador', 'Estado de orden de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ORDEN_COMPRA.PENDIENTE', 'Pendiente', 'Estado de orden de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ORDEN_COMPRA.APROBADA', 'Aprobada', 'Estado de orden de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ORDEN_COMPRA.ENVIADA', 'Enviada', 'Estado de orden de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ORDEN_COMPRA.CONFIRMADA_PROVEEDOR', 'Confirmada por Proveedor', 'Estado de orden de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ORDEN_COMPRA.RECIBIDA_PARCIALMENTE', 'Recibida Parcialmente', 'Estado de orden de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ORDEN_COMPRA.RECIBIDA', 'Recibida', 'Estado de orden de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_ORDEN_COMPRA.CANCELADA', 'Cancelada', 'Estado de orden de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_PROMOCION.PROGRAMADA', 'Programada', 'Estado de promoción', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_PROMOCION.ACTIVA', 'Activa', 'Estado de promoción', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_PROMOCION.AGOTADA', 'Agotada', 'Estado de promoción', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_PROMOCION.VENCIDA', 'Vencida', 'Estado de promoción', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_PROVEEDOR.ACTIVO', 'Activo', 'Estado del proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_PROVEEDOR.INACTIVO', 'Inactivo', 'Estado del proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_RECEPCION.PENDIENTE', 'Pendiente', 'Estado de recepción', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_RECEPCION.CONFORME', 'Conforme', 'Estado de recepción', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_RECEPCION.CON_DIFERENCIAS', 'Con Diferencias', 'Estado de recepción', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_SOLICITUD_COMPRA.BORRADOR', 'Borrador', 'Estado de solicitud de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_SOLICITUD_COMPRA.PENDIENTE_APROBACION', 'Pendiente de Aprobación', 'Estado de solicitud de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_SOLICITUD_COMPRA.APROBADA', 'Aprobada', 'Estado de solicitud de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_SOLICITUD_COMPRA.RECHAZADA', 'Rechazada', 'Estado de solicitud de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_SOLICITUD_COMPRA.CONVERTIDA_OC', 'Convertida a Orden de Compra', 'Estado de solicitud de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_SOLICITUD_COMPRA.CANCELADA', 'Cancelada', 'Estado de solicitud de compra', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_TRANSFERENCIA_INVENTARIO.PENDIENTE', 'Pendiente', 'Estado de transferencia de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_TRANSFERENCIA_INVENTARIO.ENVIADA', 'Enviada', 'Estado de transferencia de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_TRANSFERENCIA_INVENTARIO.EN_TRANSITO', 'En Tránsito', 'Estado de transferencia de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_TRANSFERENCIA_INVENTARIO.RECIBIDA', 'Recibida', 'Estado de transferencia de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_TRANSFERENCIA_INVENTARIO.CANCELADA', 'Cancelada', 'Estado de transferencia de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_VACACION.SOLICITADO', 'Solicitado', 'Estado de solicitud de vacaciones', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_VACACION.APROBADO', 'Aprobado', 'Estado de solicitud de vacaciones', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_VACACION.RECHAZADO', 'Rechazado', 'Estado de solicitud de vacaciones', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_VACACION.TOMADO', 'Tomado', 'Estado de solicitud de vacaciones', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.ESTADO_VACACION.CANCELADO', 'Cancelado', 'Estado de solicitud de vacaciones', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.JORNADA_LABORAL.COMPLETA', 'Completa', 'Jornada laboral', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.JORNADA_LABORAL.PARCIAL', 'Parcial', 'Jornada laboral', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.JORNADA_LABORAL.REDUCIDA', 'Reducida', 'Jornada laboral', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO_POS.EFECTIVO', 'Efectivo', 'Método de pago POS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO_POS.TARJETA', 'Tarjeta', 'Método de pago POS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO_POS.YAPE', 'Yape', 'Método de pago POS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO_POS.PLIN', 'Plin', 'Método de pago POS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO_POS.MIXTO', 'Mixto', 'Método de pago POS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.METODO_PAGO_POS.GIFT_CARD', 'Gift Card', 'Método de pago POS', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_COMPRA.PRODUCTO_DEFECTUOSO', 'Producto Defectuoso', 'Motivo de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_COMPRA.PRODUCTO_DANADO_TRANSPORTE', 'Producto Dañado en Transporte', 'Motivo de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_COMPRA.DIFERENCIA_CANTIDAD', 'Diferencia en Cantidad', 'Motivo de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_COMPRA.PRODUCTO_INCORRECTO', 'Producto Incorrecto', 'Motivo de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_COMPRA.VENCIDO_O_PROXIMO_VENCER', 'Producto Vencido o Próximo a Vencer', 'Motivo de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_COMPRA.NO_CUMPLE_ESPECIFICACION', 'No Cumple Especificación Técnica', 'Motivo de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_COMPRA.ERROR_FACTURACION', 'Error de Facturación', 'Motivo de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_COMPRA.OTROS', 'Otros', 'Motivo de devolución a proveedor', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_LOGISTICA.PRODUCTO_DEFECTUOSO', 'Producto defectuoso', 'Motivo de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_LOGISTICA.PRODUCTO_INCORRECTO', 'Producto incorrecto', 'Motivo de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_LOGISTICA.ENTREGA_TARDIA', 'No llegó en el tiempo acordado', 'Motivo de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_LOGISTICA.CAMBIO_OPINION', 'El cliente cambió de opinión', 'Motivo de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_LOGISTICA.DANIO_TRANSPORTE', 'Daño en el transporte', 'Motivo de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_DEVOLUCION_LOGISTICA.OTRO', 'Otro', 'Motivo de devolución logística', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.13', 'Otros', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.14', 'Venta sujeta a confirmación del comprador', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.18', 'Traslado emisor itinerante CP', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.19', 'Traslado a zona primaria', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.01', 'Venta', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.02', 'Compra', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.04', 'Traslado entre establecimientos de la misma empresa', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.08', 'Importación', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.MOTIVO_TRASLADO_SUNAT.09', 'Exportación', 'Motivo de traslado SUNAT', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.PRIORIDAD_SOLICITUD.BAJA', 'Baja', 'Prioridad de solicitud', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.PRIORIDAD_SOLICITUD.NORMAL', 'Normal', 'Prioridad de solicitud', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.PRIORIDAD_SOLICITUD.ALTA', 'Alta', 'Prioridad de solicitud', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.PRIORIDAD_SOLICITUD.URGENTE', 'Urgente', 'Prioridad de solicitud', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.RESULTADO_MATCH_3VIA.OK_TOTAL', 'OK Total', 'Resultado de conciliación 3 vías', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.RESULTADO_MATCH_3VIA.OK_PARCIAL', 'OK Parcial', 'Resultado de conciliación 3 vías', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.RESULTADO_MATCH_3VIA.DIFERENCIA_CANTIDAD_RECIBIDA', 'Diferencia en Cantidad Recibida', 'Resultado de conciliación 3 vías', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.RESULTADO_MATCH_3VIA.DIFERENCIA_CANTIDAD_PEDIDA', 'Diferencia en Cantidad Pedida', 'Resultado de conciliación 3 vías', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.RESULTADO_MATCH_3VIA.DIFERENCIA_PRECIO', 'Diferencia en Precio', 'Resultado de conciliación 3 vías', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CPE.BOLETA', 'Boleta', 'Tipo de comprobante de pago electrónico', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CPE.FACTURA', 'Factura', 'Tipo de comprobante de pago electrónico', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CPE.SIN_CPE', 'Sin CPE', 'Tipo de comprobante de pago electrónico', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_PCGE.ACTIVO', 'Activo', 'Tipo de cuenta contable PCGE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_PCGE.PASIVO', 'Pasivo', 'Tipo de cuenta contable PCGE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_PCGE.PATRIMONIO', 'Patrimonio', 'Tipo de cuenta contable PCGE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_PCGE.RESULTADO', 'Resultado (Gastos/Ingresos)', 'Tipo de cuenta contable PCGE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_CUENTA_PCGE.ANALITICA', 'Analítica (Cuentas de Orden/Analíticas)', 'Tipo de cuenta contable PCGE', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_EVALUACION.ANUAL', 'Anual', 'Tipo de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_EVALUACION.SEMESTRAL', 'Semestral', 'Tipo de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_EVALUACION.TRIMESTRAL', 'Trimestral', 'Tipo de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_EVALUACION.PERIODO_PRUEBA', 'Periodo de Prueba', 'Tipo de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_EVALUACION.PROMOCION', 'Promoción', 'Tipo de evaluación', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.ENTRADA_COMPRA', 'Entrada por Compra', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.ENTRADA_DEVOLUCION', 'Entrada por Devolución', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.ENTRADA_AJUSTE', 'Entrada por Ajuste', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.ENTRADA_TRANSFERENCIA', 'Entrada por Transferencia', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.ENTRADA_PRODUCCION', 'Entrada por Producción', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.SALIDA_VENTA', 'Salida por Venta', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.SALIDA_DEVOLUCION', 'Salida por Devolución', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.SALIDA_AJUSTE', 'Salida por Ajuste', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.SALIDA_TRANSFERENCIA', 'Salida por Transferencia', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.SALIDA_CONSUMO', 'Salida por Consumo', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_MOVIMIENTO_INVENTARIO.SALIDA_MERMA', 'Salida por Merma', 'Tipo de movimiento de inventario', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REGISTRO_ASISTENCIA.NORMAL', 'Normal', 'Tipo de registro de asistencia', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REGISTRO_ASISTENCIA.TARDANZA', 'Tardanza', 'Tipo de registro de asistencia', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REGISTRO_ASISTENCIA.FALTA', 'Falta', 'Tipo de registro de asistencia', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REGISTRO_ASISTENCIA.PERMISO', 'Permiso', 'Tipo de registro de asistencia', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REGISTRO_ASISTENCIA.LICENCIA', 'Licencia', 'Tipo de registro de asistencia', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_REGISTRO_ASISTENCIA.VACACIONES', 'Vacaciones', 'Tipo de registro de asistencia', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_SERVICIO_TRANSPORTISTA.STANDARD', 'Estándar', 'Tipo de servicio de transportista', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_SERVICIO_TRANSPORTISTA.EXPRESS', 'Express', 'Tipo de servicio de transportista', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_SERVICIO_TRANSPORTISTA.SAME_DAY', 'Mismo Día', 'Tipo de servicio de transportista', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_SERVICIO_TRANSPORTISTA.NEXT_DAY', 'Día Siguiente', 'Tipo de servicio de transportista', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog'),
  (NULL, 'CATALOGO', 'CATALOGO.TIPO_SERVICIO_TRANSPORTISTA.INTERNATIONAL', 'Internacional', 'Tipo de servicio de transportista', true, NOW(), 'SYSTEM', NOW(), 'SYSTEM', true, false, 'catalog')
ON CONFLICT (tenant_id, param_key) DO NOTHING;
